/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.ts",
        "./resources/**/*.vue",
    ],
    media: false,
    theme: {
        colors: {
            "gray/100": "#F3F4F6",
            "gray/400": "#9CA3AF",
            "grey-500": "#6B7280",
            "gray/600": "#4B5563",
            "gray/700": "#374151",
            "grey-900": "#0C0B10",
            "black": "black",
            "light-black": "rgba(12, 11, 16, 0.5)",
            "light-grey": "rgba(9,10,10,0.1)",
            white: "#ffffff",
            "light-border": "rgba(255, 255, 255, 0.2)",
            light: "rgba(255, 255, 255, 0.6)",
            "blure-bg": "rgba(12, 11, 16, 0.2)",
            primary: "#0158A8",
            'light-primary': "#EBF2F8",
            bg: "#F3EFEF",
            "bg-light": "#FAFAFA",
            secondary: "#E04F4E",
            success: "#42BE65",
            error: "#FA4D56",
            "border-color": "#d1d5db",
        },
        screens: {
            "mob-320": "320px",
            "mob-360": "360px",
            "mob-428": "428px",
            "tab-small": "834px",
            "HD": "1024px",
            "full-HD": "1368px",
            "2K": "2560px",
        },
        borderRadius: {
            btn: "40px",
        },
        extend: {
            spacing: {
                containter: "200px",
                x10: "10px",
                xs: "14px",
                sm: "16px",
                x20: "20px",
                x25: "25px",
                x30: "30px",
                x50: "50px",
                x60: "60px",
                x70: "70px",
                x85: "85px",
                x88: "88px",
                x105: "105px",
                x100: "100px",
                x120: "120px",
                x140: "140px",
                x200: "200px",
                "mobile-container": "24px",
                li: "40px",
                normal: "48px",
                section: "247px",
                "section-lg": "480px",
                "footer-section-md": "176px",
                "footer-section-sm": "80px",
            },
            width: {
                "select-sm": "100%",
            },
            maxWidth: {
                content: "max-content",
            },
            minWidth: {},
            width: {
                inherit: "inherit",
                "min-content": "min-content",
                full: "100%"
            },
            height: {
                full: "100%",
                fit: "fit-content"
            },
            translate: {},
            borderRadius: {
                normal: "10px",
            },
            zIndex: {
                1: "1",
                max: 9999,
            },
            boxShadow: {
                cardShadow: "0px 10px 34px rgba(29, 33, 45, 0.08)",
                selectShadow: "0px 17px 31px rgba(81, 81, 81, 0.19)",
                container: "0px -3px 12px rgba(0, 0, 0, 0.05)"
            },
            fontSize: {
                xxl: "40px",
                xl: "32px",
                lg: "28px",
                m: "24px",
                base: "18px",
                xs: "16px",
                xxs: "14px",
                x20: "20px",
                x156: "156px",
                x108: "108px",
                x96: "96px",
                "hero-title": "70px",
                "hero-lg": "132px",
            },
            lineHeight: {
                m: "27px",
                normal: "30px",
                x42: "42px",
                x48: "48px",
                lg: "52px",
                x54: "54px",
                "footer-lg": "172px",
                "footer-md": "130px",
                "footer-sm": "115px",
                "footer-xs": "94px",
                "title-md": "72px",
            },
            gridTemplateColumns: {
                "4-cols": "repeat(4, auto)",
                "3-cols": "repeat(3, auto)",
                "2-cols": "repeat(2, auto)",
                "1-cols": "repeat(1, auto)",
            },
            backgroundImage: {
                linear:
                    "linear-gradient(359.87deg, #000000 -78.69%, rgba(0, 0, 0, 0) 57.34%)",
            },
        },
    },
    variants: {
        display: ["hover", "focus", "responsive"],
        cursor: ["hover", "focus", "disabled"],
        borderStyle: ["last"],
        ringOffsetWidth: ["hover", "active"],
        backgroundColor: ["disabled", "responsive"],
        textColor: ["disabled", "hover"],
        height: ["hover", "group-hover", "responsive"],
        overscrollBehavior: ["responsive"],
    },
};
